spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/hkr_blog?characterEncoding=utf-8
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/Mapper.xml #配置扫描xml文件路径
server:
  port: 8080
  servlet:
    context-path: /api